### ISSUE TITLE
Failing build on not finding module `qs`.

### ISSUE THREAD

**Issue by anusaini** [gabrielcsapo/build.sh#4]
```
build.sh  (master) - Tue Nov 14 10:50:20 $
build
module.js:515
    throw err;
    ^

Error: Cannot find module 'qs'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/anusaini/.nvm/versions/node/v8.8.1/lib/node_modules/build.sh/bin/build.js:10:12)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

```
build.sh  (master) - Tue Nov 14 10:51:46 $
node -v
v8.8.1

build.sh  (master) - Tue Nov 14 10:52:42 $
npm -v
5.5.1
```

```
build.sh  (master) - Tue Nov 14 10:52:44 $
gloten
8499e40 (HEAD -> master, upstream/master, origin/master, origin/HEAD) Merge pull request #3 from anusaini/master
7b71f7b Moving to psychic.css from psychic-ui
ec32a61 updates location of lcov-server and starbuck
c4d6f1e Update .travis.yml
5bbf337 updates docs page
c0dec86 (tag: 0.2.7) 0.2.7 - adds babel-minify-webpack-plugin which reduces build output from 345K to 263 KB
7a15514 (tag: 0.2.6) 0.2.6 - fixes broken event emitter due to async - fixes issue with nested runs - allows the ability to run parts of the pipeline - updates to react 16.0.0, slims example build output from 898 KB to 343K
b5b89db (tag: 0.2.5) 0.2.5 - adds env config to override process environment variables during build
90f8ebe updates travis.yml and readme to have badges
b592c81 (tag: 0.2.4) 0.2.4 - generates a similar pipeline view in the console
```

**Comment by anusaini** [comment]
How do I run `build` on build? 
Also, how do I install globally from the repo instead of `npm i -g build.sh`?

**Comment by anusaini** [comment]
```
which build
/Users/anusaini/.nvm/versions/node/v8.8.1/bin/build
```

**Comment by gabrielcsapo** [comment]
fixed in https://github.com/gabrielcsapo/build.sh/releases/tag/0.2.9 can you try?

**Comment by anusaini** [comment]
That got fixed. But there's another error:

```
build.sh  (master) - Tue Nov 14 11:58:10 $
build
  ── foo ── install ── lint ── coverage ── test ── docs
Capturing git information
Compile has failed with the following error:
ModuleParseError: Module parse failed: Unexpected token (16:21)
You may need an appropriate loader to handle this file type.
|     this.state = {
|       hash: location.hash,
|       selectedStage: <Stages name={props.pipeline[0].name} stages={props.pipeline[0].stages}/>
|     };
|   }

```

**Comment by anusaini** [comment]
Also get these warnings while `npm i`

```
npm i
npm WARN react-komposer@1.13.1 requires a peer of react@^0.14.3 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-komposer@2.0.0 requires a peer of react@^0.14.7 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-di@1.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-stubber@1.0.0 requires a peer of react@^0.14.7 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by gabrielcsapo** [comment]
@anusaini I am working on a fix / rewrite of the main components, will update this thread when I get something pushed.

**Comment by gabrielcsapo** [comment]
@anusaini I finally got some extra time to work on a fix, tons of bugs, tons of fixes, should be pushing something tomorrow.

**Comment by gabrielcsapo** [comment]
@anusaini as promised! https://github.com/gabrielcsapo/build.sh/releases/tag/1.0.0 🎉 Let me know what you think!

**Comment by anusaini** [comment]
Yup It works. Awesome work.

**Comment by gabrielcsapo** [comment]
@anusaini awesome! Thank you 😄 do you have anything that you would like to see added?
